/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./*.{html,js}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline-variant": "rgb(var(--co-outline-variant) / <alpha-value>)",
        "surface-tint": "rgb(var(--co-surface-tint) / <alpha-value>)",
        "on-surface-variant": "rgb(var(--co-on-surface-variant) / <alpha-value>)",
        error: "rgb(var(--co-error) / <alpha-value>)",
        "inverse-primary": "rgb(var(--co-inverse-primary) / <alpha-value>)",
        "error-container": "rgb(var(--co-error-container) / <alpha-value>)",
        "on-tertiary-container": "rgb(var(--co-on-tertiary-container) / <alpha-value>)",
        background: "rgb(var(--co-background) / <alpha-value>)",
        "on-primary": "rgb(var(--co-on-primary) / <alpha-value>)",
        outline: "rgb(var(--co-outline) / <alpha-value>)",
        "tertiary-fixed-dim": "rgb(var(--co-tertiary-fixed-dim) / <alpha-value>)",
        "on-error": "rgb(var(--co-on-error) / <alpha-value>)",
        tertiary: "rgb(var(--co-tertiary) / <alpha-value>)",
        secondary: "rgb(var(--co-secondary) / <alpha-value>)",
        "on-tertiary": "rgb(var(--co-on-tertiary) / <alpha-value>)",
        "surface-container-low": "rgb(var(--co-surface-container-low) / <alpha-value>)",
        "surface-container": "rgb(var(--co-surface-container) / <alpha-value>)",
        "primary-fixed": "rgb(var(--co-primary-fixed) / <alpha-value>)",
        "secondary-fixed": "rgb(var(--co-secondary-fixed) / <alpha-value>)",
        "surface-container-highest": "rgb(var(--co-surface-container-highest) / <alpha-value>)",
        "primary-container": "rgb(var(--co-primary-container) / <alpha-value>)",
        "on-primary-fixed-variant": "rgb(var(--co-on-primary-fixed-variant) / <alpha-value>)",
        "surface-container-high": "rgb(var(--co-surface-container-high) / <alpha-value>)",
        "on-primary-container": "rgb(var(--co-on-primary-container) / <alpha-value>)",
        "on-secondary-container": "rgb(var(--co-on-secondary-container) / <alpha-value>)",
        "secondary-container": "rgb(var(--co-secondary-container) / <alpha-value>)",
        "surface-container-lowest": "rgb(var(--co-surface-container-lowest) / <alpha-value>)",
        "inverse-surface": "rgb(var(--co-inverse-surface) / <alpha-value>)",
        "on-tertiary-fixed": "rgb(var(--co-on-tertiary-fixed) / <alpha-value>)",
        surface: "rgb(var(--co-surface) / <alpha-value>)",
        "primary-fixed-dim": "rgb(var(--co-primary-fixed-dim) / <alpha-value>)",
        "on-secondary": "rgb(var(--co-on-secondary) / <alpha-value>)",
        "surface-bright": "rgb(var(--co-surface-bright) / <alpha-value>)",
        "on-surface": "rgb(var(--co-on-surface) / <alpha-value>)",
        "secondary-fixed-dim": "rgb(var(--co-secondary-fixed-dim) / <alpha-value>)",
        "on-secondary-fixed-variant": "rgb(var(--co-on-secondary-fixed-variant) / <alpha-value>)",
        "on-secondary-fixed": "rgb(var(--co-on-secondary-fixed) / <alpha-value>)",
        "surface-variant": "rgb(var(--co-surface-variant) / <alpha-value>)",
        "on-primary-fixed": "rgb(var(--co-on-primary-fixed) / <alpha-value>)",
        "tertiary-fixed": "rgb(var(--co-tertiary-fixed) / <alpha-value>)",
        "inverse-on-surface": "rgb(var(--co-inverse-on-surface) / <alpha-value>)",
        "on-background": "rgb(var(--co-on-background) / <alpha-value>)",
        "surface-dim": "rgb(var(--co-surface-dim) / <alpha-value>)",
        primary: "rgb(var(--co-primary) / <alpha-value>)",
        "on-tertiary-fixed-variant": "rgb(var(--co-on-tertiary-fixed-variant) / <alpha-value>)",
        "tertiary-container": "rgb(var(--co-tertiary-container) / <alpha-value>)",
        "on-error-container": "rgb(var(--co-on-error-container) / <alpha-value>)",
      },
      fontFamily: {
        headline: ["Epilogue"],
        body: ["Plus Jakarta Sans"],
        label: ["Space Grotesk"],
        editorial: ["Bricolage Grotesque"],
        mono: ["JetBrains Mono"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
